# Generated by Django 4.1.5 on 2023-09-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_ID",
            field=models.CharField(max_length=100),
        ),
    ]
