# Generated by Django 4.1.5 on 2023-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_company_slug_employee_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="roles",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
