# Generated by Django 4.1.5 on 2023-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_roles_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Roles",
        ),
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
