# Generated by Django 4.1.5 on 2023-09-14 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_company_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_employed",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
