# Generated by Django 4.1.5 on 2023-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_employee_date_employed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="reg_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
