# Generated by Django 4.1.5 on 2023-09-14 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_alter_company_created_alter_employee_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_left",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
