# Generated by Django 4.1.5 on 2023-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_employee_date_left"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="reg_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
