# Generated by Django 4.1.5 on 2023-09-14 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_alter_company_reg_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="reg_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
