# Generated by Django 4.1.5 on 2023-09-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_alter_company_reg_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=300)),
                ("role", models.CharField(max_length=100)),
                ("duties", models.TextField(blank=True, null=True)),
                ("date_started", models.DateField()),
                ("date_ended", models.DateField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
